CREATE TABLE Investor
(
	Id BIGINT IDENTITY(1, 1),
	Name VARCHAR(2000) NOT NULL,
	InvestorTypeId BIGINT,
	Address VARCHAR(MAX) NOT NULL,
	AddedOn DATETIME NOT NULL,
	EditedOn DATETIME NOT NULL
)

ALTER TABLE Investor
ADD CONSTRAINT PK_Investor PRIMARY KEY (Id);

ALTER TABLE Investor
ADD CONSTRAINT FK_Investor_InvestorType FOREIGN KEY (InvestorTypeId) REFERENCES InvestorType(Id);

GO

CREATE TABLE Commitment
(
	Id BIGINT IDENTITY(1, 1),
	InvestorId BIGINT,
	AssetClassId BIGINT,
	CurrencyId BIGINT,
	Amount DECIMAL NOT NULL,
	AddedOn DATETIME NOT NULL,
	EditedOn DATETIME NOT NULL,
)

ALTER TABLE Commitment
ADD CONSTRAINT PK_Commitment PRIMARY KEY (Id);

ALTER TABLE Commitment
ADD CONSTRAINT FK_Commitment_Investor FOREIGN KEY (InvestorId) REFERENCES Investor(Id);

ALTER TABLE Commitment
ADD CONSTRAINT FK_Commitment_AssetClass FOREIGN KEY (AssetClassId) REFERENCES AssetClass(Id);

ALTER TABLE Commitment
ADD CONSTRAINT FK_Commitment_Currency FOREIGN KEY (CurrencyId) REFERENCES Currency(Id);

GO

CREATE TABLE InvestorType
(
	Id BIGINT IDENTITY(1, 1),
	Name VARCHAR(2000) NOT NULL,
	AddedOn DATETIME NOT NULL,
	EditedOn DATETIME NOT NULL
)

ALTER TABLE InvestorType
ADD CONSTRAINT PK_InvestorType PRIMARY KEY (Id);

GO

CREATE TABLE AssetClass
(
	Id BIGINT IDENTITY(1, 1),
	Name VARCHAR(2000) NOT NULL,
	AddedOn DATETIME NOT NULL,
	EditedOn DATETIME NOT NULL
)

ALTER TABLE AssetClass
ADD CONSTRAINT PK_AssetClass PRIMARY KEY (Id);

GO

CREATE TABLE Currency
(
	Id BIGINT IDENTITY(1, 1),
	Name VARCHAR(2000) NOT NULL,
	AddedOn DATETIME NOT NULL,
	EditedOn DATETIME NOT NULL
)

ALTER TABLE Currency
ADD CONSTRAINT PK_Currency PRIMARY KEY (Id);

GO
